# Generated by Django 5.0 on 2024-01-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0003_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontmentmodel',
            name='appointment_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='appiontmentmodel',
            name='appointment_type',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=30),
        ),
        migrations.AlterField(
            model_name='appiontmentmodel',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletimemodel'),
        ),
    ]
