# Generated by Django 5.0 on 2024-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='available_time',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='available_time',
            field=models.ManyToManyField(to='doctor.availabletimemodel'),
        ),
    ]
